<form method="post">
    <select name="grade1">
        <option value="kiezen" disabled selected>Kiezen...</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="4">5</option>
        <option value="4">6</option>
        <option value="4">7</option>
        <option value="4">8</option>
        <option value="4">9</option>
        <option value="4">10</option>
    </select>
    <select name="grade2">
        <option value="kiezen" disabled selected>Kiezen...</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="4">5</option>
        <option value="4">6</option>
        <option value="4">7</option>
        <option value="4">8</option>
        <option value="4">9</option>
        <option value="4">10</option>
    </select>
    <select name="grade3">
        <option value="kiezen" disabled selected>Kiezen...</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="4">5</option>
        <option value="4">6</option>
        <option value="4">7</option>
        <option value="4">8</option>
        <option value="4">9</option>
        <option value="4">10</option>
    </select>
    <select name="grade4">
        <option value="kiezen" disabled selected>Kiezen...</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="4">5</option>
        <option value="4">6</option>
        <option value="4">7</option>
        <option value="4">8</option>
        <option value="4">9</option>
        <option value="4">10</option>
    </select>
    <select name="grade5">
        <option value="kiezen" disabled selected>Kiezen...</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="4">5</option>
        <option value="4">6</option>
        <option value="4">7</option>
        <option value="4">8</option>
        <option value="4">9</option>
        <option value="4">10</option>
    </select>
    <select name="grade6">
        <option value="kiezen" disabled selected>Kiezen...</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="4">5</option>
        <option value="4">6</option>
        <option value="4">7</option>
        <option value="4">8</option>
        <option value="4">9</option>
        <option value="4">10</option>
    </select>
    <select name="grade7">
        <option value="kiezen" disabled selected>Kiezen...</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="4">5</option>
        <option value="4">6</option>
        <option value="4">7</option>
        <option value="4">8</option>
        <option value="4">9</option>
        <option value="4">10</option>
    </select>
    <select name="grade8">
        <option value="kiezen" disabled selected>Kiezen...</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="4">5</option>
        <option value="4">6</option>
        <option value="4">7</option>
        <option value="4">8</option>
        <option value="4">9</option>
        <option value="4">10</option>
    </select>
    <input type="submit">
</form>